# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bgrpbx1 = QtWidgets.QGroupBox(self.centralwidget)
        self.bgrpbx1.setGeometry(QtCore.QRect(10, 10, 541, 531))
        self.bgrpbx1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.bgrpbx1.setObjectName("bgrpbx1")
        self.rdbtn1 = QtWidgets.QRadioButton(self.bgrpbx1)
        self.rdbtn1.setGeometry(QtCore.QRect(10, 190, 131, 20))
        self.rdbtn1.setObjectName("rdbtn1")
        self.rdbtn2 = QtWidgets.QRadioButton(self.bgrpbx1)
        self.rdbtn2.setGeometry(QtCore.QRect(180, 190, 131, 20))
        self.rdbtn2.setObjectName("rdbtn2")
        self.rdbtn3 = QtWidgets.QRadioButton(self.bgrpbx1)
        self.rdbtn3.setGeometry(QtCore.QRect(390, 190, 131, 20))
        self.rdbtn3.setObjectName("rdbtn3")
        self.Lbl2 = QtWidgets.QLabel(self.bgrpbx1)
        self.Lbl2.setGeometry(QtCore.QRect(20, 410, 121, 16))
        self.Lbl2.setObjectName("Lbl2")
        self.Lbl1 = QtWidgets.QLabel(self.bgrpbx1)
        self.Lbl1.setGeometry(QtCore.QRect(10, 60, 151, 16))
        self.Lbl1.setObjectName("Lbl1")
        self.Btn1 = QtWidgets.QPushButton(self.bgrpbx1)
        self.Btn1.setGeometry(QtCore.QRect(440, 60, 75, 23))
        self.Btn1.setObjectName("Btn1")
        self.TxtEdt1 = QtWidgets.QTextEdit(self.bgrpbx1)
        self.TxtEdt1.setGeometry(QtCore.QRect(10, 260, 491, 151))
        self.TxtEdt1.setObjectName("TxtEdt1")
        self.Edt2 = QtWidgets.QLineEdit(self.bgrpbx1)
        self.Edt2.setGeometry(QtCore.QRect(30, 440, 271, 20))
        self.Edt2.setObjectName("Edt2")
        self.Btn2 = QtWidgets.QPushButton(self.bgrpbx1)
        self.Btn2.setGeometry(QtCore.QRect(340, 440, 75, 23))
        self.Btn2.setObjectName("Btn2")
        self.Btn3 = QtWidgets.QPushButton(self.bgrpbx1)
        self.Btn3.setGeometry(QtCore.QRect(20, 490, 75, 23))
        self.Btn3.setObjectName("Btn3")
        self.Btn5 = QtWidgets.QPushButton(self.bgrpbx1)
        self.Btn5.setGeometry(QtCore.QRect(380, 490, 75, 23))
        self.Btn5.setObjectName("Btn5")
        self.Btn4 = QtWidgets.QPushButton(self.bgrpbx1)
        self.Btn4.setGeometry(QtCore.QRect(210, 490, 75, 23))
        self.Btn4.setObjectName("Btn4")
        self.LblCentro = QtWidgets.QLabel(self.bgrpbx1)
        self.LblCentro.setGeometry(QtCore.QRect(20, 100, 51, 16))
        self.LblCentro.setObjectName("LblCentro")
        self.Lblcrd = QtWidgets.QLabel(self.bgrpbx1)
        self.Lblcrd.setGeometry(QtCore.QRect(20, 140, 451, 16))
        self.Lblcrd.setObjectName("Lblcrd")
        self.cmb1 = QtWidgets.QComboBox(self.bgrpbx1)
        self.cmb1.setGeometry(QtCore.QRect(160, 60, 261, 22))
        self.cmb1.setObjectName("cmb1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VectorFile"))
        self.bgrpbx1.setTitle(_translate("MainWindow", "informacion de entrada"))
        self.rdbtn1.setText(_translate("MainWindow", "Leer atributos"))
        self.rdbtn2.setText(_translate("MainWindow", "Editar atributos"))
        self.rdbtn3.setText(_translate("MainWindow", "Eliminar atributos"))
        self.Lbl2.setText(_translate("MainWindow", "informacion de salida"))
        self.Lbl1.setText(_translate("MainWindow", "Selleciona un archivo vetorial"))
        self.Btn1.setText(_translate("MainWindow", "..."))
        self.Btn2.setText(_translate("MainWindow", "..."))
        self.Btn3.setText(_translate("MainWindow", "ayuda"))
        self.Btn5.setText(_translate("MainWindow", "cancelar"))
        self.Btn4.setText(_translate("MainWindow", "ejecutar"))
        self.LblCentro.setText(_translate("MainWindow", "Centroide"))
        self.Lblcrd.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
